### ISSUE TITLE
Support Internationalized Resource Identifiers

### ISSUE THREAD

**Issue by Laxystem** [eygraber/uri-kmp#312]
Does the `Uri` class support [IRI](https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier)s (that is, URIs that support unicode characters)? If not, could you please add support for them, as an add-on module perhaps?

They're used by JsonLD, therefore ActivityPub, therefore the Fediverse.

**Comment by eygraber** [comment]
I'm not sure if it is currently supported or not. If you provide me with a sample I can try it. 

If it isn't already supported, I'm not sure when I'd have time to add support, so it would probably have to be an external contribution.

**Comment by Laxystem** [comment]
> I'm not sure if it is currently supported or not. If you provide me with a sample I can try it.

You could check out this website, [ישראלי.ישראל](http://ישראלי.ישראל), aka [xn--4dbrbl2df.xn--4dbrk0ce](http://xn--4dbrbl2df.xn--4dbrk0ce/).

**Comment by eygraber** [comment]
Ran a quick test and it appears to be supported.

**Comment by Laxystem** [comment]
> Ran a quick test and it appears to be supported.

Amazing, then --- thanks!
